name: JUnit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test with Gradle
        run: ./gradlew test
